<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Bread; // Model ismin Bread olduğu için bu şekilde bırakıldı
use Illuminate\Support\Facades\DB;

class BreadSeeder extends Seeder
{
    public function run()
    {
        // ID'nin 1'den başlaması için tabloyu boşaltıyoruz
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Bread::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $breeds = [
            ['en' => 'Pawfect Mix', 'tr' => 'Mükemmel Melez'],
            ['en' => 'Afghan Hound', 'tr' => 'Afgan Tazısı'],
            ['en' => 'Airedale Terrier', 'tr' => 'Airedale Terrier'],
            ['en' => 'Akita', 'tr' => 'Akita'],
            ['en' => 'Alaskan Malamute', 'tr' => 'Alaska Kurdu'],
            ['en' => 'American Eskimo Dog', 'tr' => 'Amerikan Eskimo Köpeği'],
            ['en' => 'American Hairless Terrier', 'tr' => 'Amerikan Tüysüz Terrier'],
            ['en' => 'American Staffordshire Terrier', 'tr' => 'Amerikan Staffordshire Terrier'],
            ['en' => 'American Water Spaniel', 'tr' => 'Amerikan Su Spanieli'],
            ['en' => 'Anatolian Shepherd Dog', 'tr' => 'Anadolu Çoban Köpeği'],
            ['en' => 'Australian Cattle Dog', 'tr' => 'Avustralya Sığır Köpeği'],
            ['en' => 'Australian Shepherd', 'tr' => 'Avustralya Çoban Köpeği'],
            ['en' => 'Australian Terrier', 'tr' => 'Avustralya Terrier'],
            ['en' => 'Basenji', 'tr' => 'Basenji'],
            ['en' => 'Basset Hound', 'tr' => 'Basset Hound'],
            ['en' => 'Beagle', 'tr' => 'Beagle'],
            ['en' => 'Bearded Collie', 'tr' => 'Sakallı Collie'],
            ['en' => 'Bedlington Terrier', 'tr' => 'Bedlington Terrier'],
            ['en' => 'Belgian Malinois', 'tr' => 'Belçika Malinois'],
            ['en' => 'Belgian Sheepdog', 'tr' => 'Belçika Çoban Köpeği'],
            ['en' => 'Belgian Tervuren', 'tr' => 'Belçika Tervuren'],
            ['en' => 'Bernese Mountain Dog', 'tr' => 'Bernese Dağ Köpeği'],
            ['en' => 'Bichon Frise', 'tr' => 'Bişon Çuha'],
            ['en' => 'Black and Tan Coonhound', 'tr' => 'Siyah ve Bronz Rakun Tazısı'],
            ['en' => 'Black Russian Terrier', 'tr' => 'Siyah Rus Terrier'],
            ['en' => 'Bloodhound', 'tr' => 'Bloodhound'],
            ['en' => 'Border Collie', 'tr' => 'Border Collie'],
            ['en' => 'Border Terrier', 'tr' => 'Border Terrier'],
            ['en' => 'Borzoi', 'tr' => 'Rus Tazısı (Borzoi)'],
            ['en' => 'Boston Terrier', 'tr' => 'Boston Terrier'],
            ['en' => 'Bouvier des Flandres', 'tr' => 'Flandre Çoban Köpeği'],
            ['en' => 'Boxer', 'tr' => 'Boxer'],
            ['en' => 'Boykin Spaniel', 'tr' => 'Boykin Spaniel'],
            ['en' => 'Briard', 'tr' => 'Briard'],
            ['en' => 'Brittany', 'tr' => 'Brittany'],
            ['en' => 'Brussels Griffon', 'tr' => 'Brüksel Griffonu'],
            ['en' => 'Bull Terrier', 'tr' => 'Bull Terrier'],
            ['en' => 'Bulldog', 'tr' => 'Bulldog'],
            ['en' => 'Bullmastiff', 'tr' => 'Bullmastiff'],
            ['en' => 'Cairn Terrier', 'tr' => 'Cairn Terrier'],
            ['en' => 'Canaan Dog', 'tr' => 'Kenan Köpeği'],
            ['en' => 'Cane Corso', 'tr' => 'Cane Corso'],
            ['en' => 'Cardigan Welsh Corgi', 'tr' => 'Cardigan Welsh Corgi'],
            ['en' => 'Cavalier King Charles Spaniel', 'tr' => 'Cavalier King Charles Spaniel'],
            ['en' => 'Cesky Terrier', 'tr' => 'Çek Terrier'],
            ['en' => 'Chesapeake Bay Retriever', 'tr' => 'Chesapeake Bay Retriever'],
            ['en' => 'Chihuahua', 'tr' => 'Şivava (Chihuahua)'],
            ['en' => 'Chinese Crested', 'tr' => 'Çin Tüysüz Köpeği'],
            ['en' => 'Chinese Shar-Pei', 'tr' => 'Çin Shar-Pei'],
            ['en' => 'Chinook', 'tr' => 'Chinook'],
            ['en' => 'Chow Chow', 'tr' => 'Çin Aslanı (Chow Chow)'],
            ['en' => 'Clumber Spaniel', 'tr' => 'Clumber Spaniel'],
            ['en' => 'Cocker Spaniel', 'tr' => 'Cocker Spaniel'],
            ['en' => 'Collie', 'tr' => 'Collie'],
            ['en' => 'Curly-Coated Retriever', 'tr' => 'Kıvırcık Tüylü Retriever'],
            ['en' => 'Dachshund', 'tr' => 'Dachshund (Sosis Köpek)'],
            ['en' => 'Dalmatian', 'tr' => 'Dalmaçyalı'],
            ['en' => 'Dandie Dinmont Terrier', 'tr' => 'Dandie Dinmont Terrier'],
            ['en' => 'Doberman Pinscher', 'tr' => 'Doberman'],
            ['en' => 'Dogue de Bordeaux', 'tr' => 'Bordeaux Grifonu'],
            ['en' => 'English Cocker Spaniel', 'tr' => 'İngiliz Cocker Spaniel'],
            ['en' => 'English Foxhound', 'tr' => 'İngiliz Tilki Tazısı'],
            ['en' => 'English Setter', 'tr' => 'İngiliz Seteri'],
            ['en' => 'English Springer Spaniel', 'tr' => 'İngiliz Springer Spaniel'],
            ['en' => 'English Toy Spaniel', 'tr' => 'İngiliz Toy Spaniel'],
            ['en' => 'Field Spaniel', 'tr' => 'Alan Spanieli'],
            ['en' => 'Finnish Lapphund', 'tr' => 'Fin Lapphund'],
            ['en' => 'Finnish Spitz', 'tr' => 'Fin Spitz'],
            ['en' => 'Flat-Coated Retriever', 'tr' => 'Düz Tüylü Retriever'],
            ['en' => 'French Bulldog', 'tr' => 'Fransız Bulldog'],
            ['en' => 'German Pinscher', 'tr' => 'Alman Pinscher'],
            ['en' => 'German Shepherd Dog', 'tr' => 'Alman Çoban Köpeği'],
            ['en' => 'German Shorthaired Pointer', 'tr' => 'Alman Kısa Tüylü Puanteri'],
            ['en' => 'German Wirehaired Pointer', 'tr' => 'Alman Sert Tüylü Puanteri'],
            ['en' => 'Giant Schnauzer', 'tr' => 'Dev Schnauzer'],
            ['en' => 'Glen of Imaal Terrier', 'tr' => 'Glen of Imaal Terrier'],
            ['en' => 'Golden Retriever', 'tr' => 'Golden Retriever'],
            ['en' => 'Gordon Setter', 'tr' => 'Gordon Seteri'],
            ['en' => 'Great Dane', 'tr' => 'Danua'],
            ['en' => 'Great Pyrenees', 'tr' => 'Pyrenees Çoban Köpeği'],
            ['en' => 'Greater Swiss Mountain Dog', 'tr' => 'Büyük İsviçre Dağ Köpeği'],
            ['en' => 'Greyhound', 'tr' => 'Greyhound'],
            ['en' => 'Harrier', 'tr' => 'Harrier'],
            ['en' => 'Havanese', 'tr' => 'Havanese'],
            ['en' => 'Ibizan Hound', 'tr' => 'Ibiza Tazısı'],
            ['en' => 'Icelandic Sheepdog', 'tr' => 'İzlanda Çoban Köpeği'],
            ['en' => 'Irish Red and White Setter', 'tr' => 'İrlanda Kırmızı ve Beyaz Seter'],
            ['en' => 'Irish Setter', 'tr' => 'İrlanda Seteri'],
            ['en' => 'Irish Terrier', 'tr' => 'İrlanda Terrier'],
            ['en' => 'Irish Water Spaniel', 'tr' => 'İrlanda Su Spanieli'],
            ['en' => 'Irish Wolfhound', 'tr' => 'İrlanda Kurt Köpeği'],
            ['en' => 'Italian Greyhound', 'tr' => 'İtalyan Tazısı'],
            ['en' => 'Japanese Chin', 'tr' => 'Japon Chin'],
            ['en' => 'Keeshond', 'tr' => 'Keeshond'],
            ['en' => 'Kerry Blue Terrier', 'tr' => 'Kerry Blue Terrier'],
            ['en' => 'Komondor', 'tr' => 'Komondor'],
            ['en' => 'Kuvasz', 'tr' => 'Kuvasz'],
            ['en' => 'Labrador Retriever', 'tr' => 'Labrador Retriever'],
            ['en' => 'Lagotto Romagnolo', 'tr' => 'Lagotto Romagnolo'],
            ['en' => 'Lakeland Terrier', 'tr' => 'Lakeland Terrier'],
            ['en' => 'Leonberger', 'tr' => 'Leonberger'],
            ['en' => 'Lhasa Apso', 'tr' => 'Lhasa Apso'],
            ['en' => 'Lowchen', 'tr' => 'Löwchen'],
            ['en' => 'Maltese', 'tr' => 'Malta Köpeği (Maltese)'],
            ['en' => 'Manchester Terrier', 'tr' => 'Manchester Terrier'],
            ['en' => 'Mastiff', 'tr' => 'Mastiff'],
            ['en' => 'Miniature American Shepherd', 'tr' => 'Minyatür Amerikan Çoban Köpeği'],
            ['en' => 'Miniature Bull Terrier', 'tr' => 'Minyatür Bull Terrier'],
            ['en' => 'Miniature Pinscher', 'tr' => 'Minyatür Pinscher'],
            ['en' => 'Miniature Schnauzer', 'tr' => 'Minyatür Schnauzer'],
            ['en' => 'Neapolitan Mastiff', 'tr' => 'Napoli Mastifi'],
            ['en' => 'Newfoundland', 'tr' => 'Newfoundland'],
            ['en' => 'Norfolk Terrier', 'tr' => 'Norfolk Terrier'],
            ['en' => 'Norwegian Elkhound', 'tr' => 'Norveç Elkhound'],
            ['en' => 'Norwegian Lundehund', 'tr' => 'Norveç Lundehund'],
            ['en' => 'Norwich Terrier', 'tr' => 'Norwich Terrier'],
            ['en' => 'Nova Scotia Duck Tolling Retriever', 'tr' => 'Nova Scotia Ördek Getirici'],
            ['en' => 'Old English Sheepdog', 'tr' => 'Eski İngiliz Çoban Köpeği'],
            ['en' => 'Otterhound', 'tr' => 'Su Samuru Tazısı'],
            ['en' => 'Papillon', 'tr' => 'Papillon (Kelebek Köpeği)'],
            ['en' => 'Parson Russell Terrier', 'tr' => 'Parson Russell Terrier'],
            ['en' => 'Pekingese', 'tr' => 'Pekinez'],
            ['en' => 'Pembroke Welsh Corgi', 'tr' => 'Pembroke Welsh Corgi'],
            ['en' => 'Petit Basset Griffon Vendéen', 'tr' => 'Petit Basset Griffon Vendéen'],
            ['en' => 'Pharaoh Hound', 'tr' => 'Firavun Tazısı'],
            ['en' => 'Plott Hound', 'tr' => 'Plott Hound'],
            ['en' => 'Pointer', 'tr' => 'Puanter (Pointer)'],
            ['en' => 'Polish Lowland Sheepdog', 'tr' => 'Polonya Ova Çoban Köpeği'],
            ['en' => 'Pomeranian', 'tr' => 'Pomeranian Boo'],
            ['en' => 'Poodle', 'tr' => 'Kaniş (Poodle)'],
            ['en' => 'Portuguese Podengo', 'tr' => 'Portekiz Podengo'],
            ['en' => 'Portuguese Water Dog', 'tr' => 'Portekiz Su Köpeği'],
            ['en' => 'Pug', 'tr' => 'Pug'],
            ['en' => 'Rat Terrier', 'tr' => 'Rat Terrier'],
            ['en' => 'Redbone Coonhound', 'tr' => 'Kızıl Rakun Tazısı'],
            ['en' => 'Rhodesian Ridgeback', 'tr' => 'Rodezya Sırtı Çizgili'],
            ['en' => 'Rottweiler', 'tr' => 'Rottweiler'],
            ['en' => 'Russell Terrier', 'tr' => 'Russell Terrier'],
            ['en' => 'Saint Bernard', 'tr' => 'St. Bernard'],
            ['en' => 'Saluki', 'tr' => 'Saluki (Gazel Tazısı)'],
            ['en' => 'Samoyed', 'tr' => 'Samoyed'],
            ['en' => 'Schipperke', 'tr' => 'Schipperke'],
            ['en' => 'Scottish Deerhound', 'tr' => 'İskoç Geyik Tazısı'],
            ['en' => 'Scottish Terrier', 'tr' => 'İskoç Terrier'],
            ['en' => 'Sealyham Terrier', 'tr' => 'Sealyham Terrier'],
            ['en' => 'Shetland Sheepdog', 'tr' => 'Shetland Çoban Köpeği'],
            ['en' => 'Shiba Inu', 'tr' => 'Shiba Inu'],
            ['en' => 'Shih Tzu', 'tr' => 'Shih Tzu'],
            ['en' => 'Siberian Husky', 'tr' => 'Sibirya Kurdu (Husky)'],
            ['en' => 'Silky Terrier', 'tr' => 'Silky Terrier'],
            ['en' => 'Skye Terrier', 'tr' => 'Skye Terrier'],
            ['en' => 'Sloughi', 'tr' => 'Sloughi (Arap Tazısı)'],
            ['en' => 'Soft Coated Wheaten Terrier', 'tr' => 'Soft Coated Wheaten Terrier'],
            ['en' => 'Spanish Water Dog', 'tr' => 'İspanyol Su Köpeği'],
            ['en' => 'Spinone Italiano', 'tr' => 'İtalyan Spinone'],
            ['en' => 'Staffordshire Bull Terrier', 'tr' => 'Staffordshire Bull Terrier'],
            ['en' => 'Standard Schnauzer', 'tr' => 'Standart Schnauzer'],
            ['en' => 'Sussex Spaniel', 'tr' => 'Sussex Spaniel'],
            ['en' => 'Tibetan Mastiff', 'tr' => 'Tibet Mastifi'],
            ['en' => 'Tibetan Spaniel', 'tr' => 'Tibet Spanieli'],
            ['en' => 'Tibetan Terrier', 'tr' => 'Tibet Terrier'],
            ['en' => 'Toy Fox Terrier', 'tr' => 'Toy Fox Terrier'],
            ['en' => 'Treeing Walker Coonhound', 'tr' => 'Treeing Walker Coonhound'],
            ['en' => 'Vizsla', 'tr' => 'Macar Puanteri (Vizsla)'],
            ['en' => 'Weimaraner', 'tr' => 'Weimaraner'],
            ['en' => 'Welsh Springer Spaniel', 'tr' => 'Welsh Springer Spaniel'],
            ['en' => 'Welsh Terrier', 'tr' => 'Welsh Terrier'],
            ['en' => 'West Highland White Terrier', 'tr' => 'West Highland White Terrier'],
            ['en' => 'Whippet', 'tr' => 'Whippet'],
            ['en' => 'Wire Fox Terrier', 'tr' => 'Tel Tüylü Fox Terrier'],
            ['en' => 'Wirehaired Pointing Griffon', 'tr' => 'Sert Tüylü Puanter Grifonu'],
            ['en' => 'Wirehaired Vizsla', 'tr' => 'Sert Tüylü Vizsla'],
            ['en' => 'Xoloitzcuintli', 'tr' => 'Meksika Tüysüz Köpeği'],
            ['en' => 'Yorkshire Terrier', 'tr' => 'Yorkshire Terrier'],
        ];

        foreach ($breeds as $data) {
            $breed = Bread::create();
            $breed->setTranslation('name', 'en', $data['en']);
            $breed->setTranslation('name', 'tr', $data['tr']);
            $breed->save();
        }
    }
}
